version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for a `package.json` and `package-lock.json` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Commit details
    commit-message:
      prefix: "fix"
      include: "scope"
